server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: 'http://localhost:8083'
          predicates:
            - Path=/api/v1/auth/**
        - id: gym-app
          uri: 'http://localhost:8081'
          predicates:
            - Path=/api/v1/gym/**

security:
  key: miclaveultrasegurasecretadefinitiva1234

logging:
  level:
    org.springframework.security: DEBUG